---
num_rounds: 3
num_clients: 10
num_classes: 5
num_clients_per_round_fit: 5
num_clients_per_round_eval: 3
batch_size: 32
config_fit:
  lr: 0.001
  momentum: 0.9
  local_epochs: 10
defaults:
  - model: net